egrita"

#~ msgid "Join the club"
#~ msgstr "Únete al club"

#~ msgid "Despacho Theme - 100% FREE"
#~ msgstr "Despacho Theme - 100% GRATIS"

#~ msgid "FREE!"
#~ msgstr "¡GRATIS!"

#~ msgid "Important Links"
#~ msgstr "Enlaces importantes"

#~ msgid "Current product is not included with your membership key"
#~ msgstr "El producto actual no está incluido en tu clave de suscripción"

#~ msgid "Membership"
#~ msgstr "Suscripción"

#~ msgid "Upgrade to Premium Version"
#~ msgstr "Actualizar a la Versión Premium"

#~ msgid ""
#~ "Have you purchased the premium version of a plugin? Don't you know how to "
#~ "activate the license after the purchase?"
#~ msgstr ""
#~ "¿Has comprado la versión premium de un plugin? ¿No sabes cómo activar la "
#~ "licencia después de la compra?"

#~ msgid ""
#~ "To upgrade from a FREE to a PREMIUM plugin is not suffice to insert the "
#~ "license key provided after the purchase.\n"
#~ "        The reason is that they are two distinct products, with "
#~ "significant differences both for available options and for number of "
#~ "files included in the plugin package.\n"
#~ "        To start to use the PREMIUM version of the plugin, you simply "
#~ "need to download the PREMIUM packet and install it on your site."
#~ msgstr ""
#~ "Para actualizar a del plugin FREE al PREMIUMT no es suficiente con "
#~ "insertar la clave de licencia proporcionada después de la compra.\n"
#~ "        La razón es que son dos productos diferentes, con diferencias "
#~ "significativas en las opciones disponibles para el número de archivos "
#~ "incluidos en el paquete del plugin.\n"
#~ "        Para empezar a usar la versión PREMIUM del plugin, simplemente "
#~ "necesitas descargar el paquete PREMIUM e instalarlo en tu sitio web."

#~ msgid ""
#~ "%1$sDo you need to know how to do it?%2$s Easy! %1$sFollow this list of "
#~ "steps%2$s and in a few minutes the plugin you purchased will be installed "
#~ "on your site"
#~ msgstr ""
#~ "%1$s¿Necesitas saber cómo hacerlo?%2$s ¡Fácil! %1$sSigue estos pasos%2$s "
#~ "y en unos minutos el plugin que has comprado estará instalado en tu sitio "
#~ "web"

#~ msgid "Go to yithemes.com and login to \"My Account\" page"
#~ msgstr "Ve a yithemes.com e inicia sesión en la página \"Mi cuenta\""

#~ msgid ""
#~ "From the menu on the left, click on \"My Downloads\", look for the plugin "
#~ "you want to install among the available downloads and click on \"Download"
#~ "\" button"
#~ msgstr ""
#~ "Desde el menú de la izquierda, haz click en \"Mis Descargas\", busca el "
#~ "plugin que te quieres descargar entre las descargas disponibles y haz "
#~ "click en el botón \"Descargar\""

#~ msgid ""
#~ "After downloading the packet, go to your website and login to WordPress "
#~ "administration area."
#~ msgstr ""
#~ "Después de descargar el paquete, ve a tu sitio web y regístrate en el "
#~ "área de administración de WordPress."

#~ msgid ""
#~ "From the menu on the left, click on \"Plugins\". You will be redirected "
#~ "to the page where you will find the complete list of all the plugins "
#~ "available on your site. Click on \"Add New\" button that you find above "
#~ "on the left to add a new plugin"
#~ msgstr ""
#~ "Desde el menú de la izquierda, haz click en \"Plugins\". Serás redirigido/"
#~ "a a la página donde podrás encontrar la lista completa de plugins "
#~ "disponible en tu sitio web. Haz click en el botón \"Añadir Nuevo\" que "
#~ "encontrarás arriba a la izquierda para añadir un nuevo plugin"

#~ msgid ""
#~ "You will be redirected to a new page where you will find, above on the "
#~ "left next to the page title, the \"Upload Plugin\" button."
#~ msgstr ""
#~ "Serás redirigido/a a una nueva página donde encontrarás, en la parte "
#~ "superior izquierda, junto al título de la página, el botón \"Actualizar "
#~ "Plugin\""

#~ msgid ""
#~ "Click on \"Upload Plugins\" button to start the upload of the PREMIUM "
#~ "version of the plugin previously downloaded. Click on \"Select File\", "
#~ "search for the download folder related to the plugin and upload the "
#~ "package. Now you only need to wait a few minutes for the upload and the "
#~ "installation on your site. (We used YITH Live Chat plugin by way of "
#~ "example)"
#~ msgstr ""
#~ "Haz click en el botón \"Actualizar Plugins\" para actualizar la versión "
#~ "premium del plugin anteriormente descargada. Haz click en \"Seleccionar "
#~ "Archivo\", busca la carpeta relacionada al plugin y actualiza el paquete. "
#~ "Ahora sólo necesitas esperar unos minutos para actualizarlo e instalarlo "
#~ "en tu sitio web. (Usamos YITH Live Chat a modo de ejemplo)"

#~ msgid "After completing the installation, click on \"Activate plugin\""
#~ msgstr ""
#~ "Después de completar la instalación, haz click en \"Activar plugin\""

#~ msgid ""
#~ "If everything worked allright, your plugin is now correctly installed on "
#~ "your website. Enjoy it :-)"
#~ msgstr ""
#~ "Si todo funcionó bien, tu plugin está ahora correctamente instalado en tu "
#~ "sitio web. Disfrútalo :-)"

#~ msgid ""
#~ "The last step is the activation of the plugin through its license key you "
#~ "received after the purchase. Click on \"License Activation\" that you "
#~ "find in \"YITH Plugins\" and insert the license key and the email address "
#~ "you used during the purchase."
#~ msgstr ""
#~ "El último paso es la activación del plugin a través de la clave de "
#